---
## Create Templates for the Peering Router ##
- name: Generate Configuration for all routers
  gather_facts: no
  connection: local
  hosts: all
  tags: [ template ]
  tasks:
    - include_vars: "ciops_input_template.yml"
    - name: create the directory for the configuration
      file: path=peering_config  state=directory
      run_once: true
    - name: Generate Configuration
      template: src={{dev_os}}/peering_template.j2 dest=peering_config/{{inventory_hostname}}-{{ nodes[inventory_hostname].jira }}-{{ nodes[inventory_hostname].name|upper }}-{{ nodes[inventory_hostname].lag_bw_1 }}G-config.txt
